package com.totalsecurity.sast.taint.model;

public enum MethodTaintBehavior {
    UNKNOWN_RETURN,
    PROPAGATE_RECEIVER_TO_RETURN,
    PROPAGATE_ARGUMENTS_TO_RETURN,
    PROPAGATE_SELECTED_ARGUMENTS_TO_RETURN,
    PROPAGATE_RECEIVER_AND_ARGUMENTS_TO_RETURN,
    CLEAN_RETURN,
    SANITIZED_RETURN
}
