package com.totalsecurity.sast.interprocedural;

public enum UnsupportedInterproceduralReason {
    AMBIGUOUS_OVERLOAD,
    UNKNOWN_ARGUMENT_TYPE,
    INCOMPATIBLE_ARGUMENT_TYPE,
    WRONG_ARITY,
    UNKNOWN_RECEIVER_TYPE,
    EXTERNAL_CLASS,
    AMBIGUOUS_CLASS,
    UNKNOWN_TARGET_METHOD,
    NO_ANALYZABLE_BODY,
    INTERFACE_DISPATCH,
    DYNAMIC_RECEIVER,
    INHERITED_METHOD,
    RECURSIVE_CALL
}
